{
  "// whitelist.py": "Traductions pour whitelist.py",
  "user_whitelisted": "L'utilisateur {user_id} est déjà sur la liste blanche.",
  "user_added_whitelist": "Utilisateur {user_id} ajouté à la liste blanche.",
  "user_not_in_whitelist": "L'utilisateur {user_id} n'est pas sur la liste blanche.",
  "user_removed_whitelist": "Utilisateur {user_id} retiré de la liste blanche.",
  "blocked_reported": "Vous avez été bloqué et signalé pour spam.",
  "warning_message": "Avertissement {current_warning}/{warning_count} : Vous ne pouvez pas contacter cet utilisateur. Veuillez cesser d'envoyer des messages, sinon vous serez bloqué.",

  "// infouser.py": "Traductions pour infouser.py",
  "command_in_groups_only": "Cette commande fonctionne uniquement dans les groupes.",
  "mention_or_reply_user": "Vous devez répondre au message d'un utilisateur ou mentionner l'utilisateur pour utiliser cette commande.",
  "about_user": "Informations sur {first_name} :",
  "user_id": "ID : {user_id}",
  "user_name": "Nom : {first_name} {last_name}",
  "user_username": "Nom d'utilisateur : @{username}",
  "user_datacenter": "Datacenter : {datacenter}",

  "// leave.py": "Traductions pour leave.py",
  "left_group": "J'ai quitté le groupe.",
  "command_groups_only": "Cette commande ne peut être utilisée que dans les groupes.",

  "// main.py": "Traductions pour main.py",
  "userbot_started": "Userbot démarré !",
  "userbot_disconnected_cancelled_error": "Userbot déconnecté en raison d'une exception CancelledError.",
  "error_occurred": "Une erreur s'est produite : {error}",
  "abort_signal_received": "Signal d'interruption reçu. Fermeture de l'Userbot...",

  "// video_downloader.py": "Traductions pour video_downloader.py",
  "video": "Vidéo : '{video_title}'",
  "video_downloaded_successfully": "Vidéo '{video_title}' téléchargée avec succès ! Envoi...",
  "error_downloading_video": "Erreur lors du téléchargement de la vidéo : {error}",

  "// copy.py": "Traductions pour copy.py",
  "copy_successfully": "Compte cloné avec succès",

  "// dellog.py": "Traductions pour dellog.py",
  "dellog_successfully": "Le fichier de log a été supprimé avec succès.",
  "dellog_missing": "Le fichier de log est manquant.",

  "// dm.py": "Traductions pour dm.py",
  "provide_username_dm": "Veuillez fournir un nom d'utilisateur et un message.",
  "user_not_found": "Utilisateur non trouvé, veuillez fournir un nom d'utilisateur valide.",
  "message_sent": "Message envoyé à @{username} !",

  "// info.py": "Traductions pour info.py",
  "system_info_title": "ℹ️ Informations système:",
  "os": "💻 OS",
  "kernel": "🔳 Noyau",
  "python_version": "🐍 Version Python",
  "telethon_version": "🤖 Version Telethon",
  "userbot_version": "⚙️ Version Userbot: ",
  "cpu_usage": "⚡ Utilisation CPU",
  "ram_usage": "📈 Utilisation RAM",
  "ram_total": "📉 RAM totale",
  "ping": "📶 Ping",
  "userbot_commands_link": "🤖 [Commandes Userbot](https://telegra.ph/Userbot-commands-09-11-46)",
  "userbot_created_by": "👤 Userbot créé par Elxes ©️",

  "// delall.py": "Traductions pour delall.py",
  "floodwait_error": "Le compte est en attente de floodwait. Attente de {waitingtime} secondes...",

  "// backup.py": "Traductions pour backup.py",
  "backup_complete": "Sauvegarde des informations terminée!",
  "backup_error": "Une erreur s'est produite lors de la sauvegarde: {error}",
  "no_backup_files": "Aucun fichier de sauvegarde trouvé.",
  "restore_complete": "Restauration terminée!",
  "restore_error": "Une erreur s'est produite lors de la restauration: {error}",

  "// weather.py": "Traductions pour weather.py",
  "ask_city": "Veuillez préciser le nom d'une ville.",
  "city_not_found": "Ville introuvable, veuillez vérifier le nom et réessayer.",
  "weather_in": "Météo à",
  "temperature": "🌡️ Température",
  "humidity": "💧 Humidité",
  "wind_speed": "🌬️ Vitesse du vent",
  "description": "🔍 Description",
  "pressure": "🔵 Pression"
}
