{
  "// whitelist.py": "Traduzioni per whitelist.py",
  "user_whitelisted": "L'utente {user_id} è già nella whitelist.",
  "user_added_whitelist": "Utente {user_id} aggiunto alla whitelist.",
  "user_not_in_whitelist": "L'utente {user_id} non è nella whitelist.",
  "user_removed_whitelist": "Utente {user_id} rimosso dalla whitelist.",
  "blocked_reported": "Sei stato bloccato e segnalato per spam.",
  "warning_message": "Avvertimento {current_warning}/{warning_count}: Non puoi contattare questo utente. Per favore, smetti di inviare messaggi, altrimenti sarai bloccato.",

  "// infouser.py": "Traduzioni per infouser.py",
  "command_in_groups_only": "Questo comando funziona solo nei gruppi.",
  "mention_or_reply_user": "Devi rispondere al messaggio di un utente o menzionare l'utente per usare questo comando.",
  "about_user": "Informazioni su {first_name}:",
  "user_id": "ID: {user_id}",
  "user_name": "Nome: {first_name} {last_name}",
  "user_username": "Username: @{username}",
  "user_datacenter": "Datacenter: {datacenter}",

  "// leave.py": "Traduzioni per leave.py",
  "left_group": "Ho lasciato il gruppo.",
  "command_groups_only": "Questo comando può essere usato solo nei gruppi.",

  "// main.py": "Traduzioni per main.py",
  "userbot_started": "Userbot avviato!",
  "userbot_disconnected_cancelled_error": "Userbot disconnesso a causa di un'eccezione CancelledError.",
  "error_occurred": "Si è verificato un errore: {error}",
  "abort_signal_received": "Segnale di interruzione ricevuto. Chiusura del Userbot...",

  "// video_downloader.py": "Traduzioni per video_downloader.py",
  "video": "Video: '{video_title}'",
  "video_downloaded_successfully": "Video '{video_title}' scaricato con successo! Invio...",
  "error_downloading_video": "Errore nel download del video: {error}",

  "// copy.py": "Traduzioni per copy.py",
  "copy_successfully": "Account clonato con successo",

  "// dellog.py": "Traduzioni per dellog.py",
  "dellog_successfully": "Il file di log è stato eliminato correttamente.",
  "dellog_missing": "Il file di log è mancante.",

  "// dm.py": "Traduzioni per dm.py",
  "provide_username_dm": "Per favore, fornisci un username e un messaggio.",
  "user_not_found": "Utente non trovato, per favore, fornisci uno username valido.",
  "message_sent": "Messaggio inviato a @{username}!",

  "// info.py": "Traduzioni per info.py",
  "system_info_title": "ℹ️ Informazioni di sistema:",
  "os": "💻 OS",
  "kernel": "🔳 Kernel",
  "python_version": "🐍 Versione Python",
  "telethon_version": "🤖 Versione Telethon",
  "userbot_version": "⚙️ Versione Userbot: ",
  "cpu_usage": "⚡ Utilizzo CPU",
  "ram_usage": "📈 Utilizzo RAM",
  "ram_total": "📉 RAM totale",
  "ping": "📶 Ping",
  "userbot_commands_link": "🤖 [Comandi Userbot](https://telegra.ph/Userbot-commands-09-11-46)",
  "userbot_created_by": "👤 Userbot creato da Elxes ©️",

  "// delall.py": "Traduzioni per delall.py",
  "floodwait_error": "L'account è in floodwait. Attendere {waitingtime} secondi...",

  "// backup.py": "Traduzioni per backup.py",
  "backup_complete": "Backup delle informazioni completato!",
  "backup_error": "Si è verificato un errore durante il backup: {error}",
  "no_backup_files": "Nessun file di backup trovato.",
  "restore_complete": "Ripristino completato!",
  "restore_error": "Si è verificato un errore durante il ripristino: {error}",

  "// weather.py": "Traduzioni per weather.py",
  "ask_city": "Per favore, specifica il nome di una città.",
  "city_not_found": "Città non trovata, controlla il nome e riprova.",
  "weather_in": "Meteo a",
  "temperature": "🌡️ Temperatura",
  "humidity": "💧 Umidità",
  "wind_speed": "🌬️ Velocità del vento",
  "description": "🔍 Descrizione",
  "pressure": "🔵 Pressione"
}
